# Generated by Django 4.2.5 on 2023-09-12 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.CharField(choices=[('RBR', 'Roads and bridges'), ('SWS', 'Sewer and waterworks'), ('POW', 'Power supply'), ('GAS', 'Gasworks'), ('TEL', 'Telecommunication'), ('GAR', 'Garbage disposal'), ('CTR', 'City transport'), ('HTH', 'Healthcare'), ('EDU', 'Education'), ('SAF', 'Public safety')], max_length=3)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('CH', 'Checking'), ('VD', 'Rejected'), ('AP', 'Approved')], default='PN', max_length=2)),
                ('clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
