# Generated by Django 4.2.5 on 2023-09-26 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='clerk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
