# Generated by Django 4.2.5 on 2023-09-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_delete_reportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('RBR', 'Roads and bridges'), ('SWS', 'Sewer and waterworks'), ('POW', 'Power supply'), ('GAS', 'Gasworks'), ('TEL', 'Telecommunication'), ('GAR', 'Garbage disposal'), ('CTR', 'City transport'), ('HTH', 'Healthcare'), ('EDU', 'Education'), ('SAF', 'Public safety')], max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('FR', 'Fresh report'), ('CH', 'Checking'), ('VD', 'Veryfied'), ('AP', 'Approved'), ('WP', 'Work in progres'), ('EW', 'Evaluation of works'), ('CD', 'Closed - done')], default='FR', max_length=2),
        ),
    ]
