# Generated by Django 4.2.5 on 2023-10-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_clerk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('CH', 'Checking'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PN', max_length=2),
        ),
    ]
