# Generated by Django 4.2.5 on 2023-09-13 13:03

import authSystem.const
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('APP', 'Applicant'), ('SYS', 'System supervisor'), ('RBR', 'Roads and bridges'), ('SWS', 'Sewer and waterworks'), ('POW', 'Power supply'), ('GAS', 'Gasworks'), ('TEL', 'Telecommunication'), ('GAR', 'Garbage disposal'), ('CTR', 'City transport'), ('HTH', 'Healthcare'), ('EDU', 'Education'), ('SAF', 'Public safety')], default=authSystem.const.Department['APP'], max_length=100),
        ),
    ]
