# Generated by Django 4.2.5 on 2023-09-21 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_newspost_clerk_alter_newspost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='clerk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
