# Generated by Django 4.2.5 on 2023-09-22 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_alter_report_options'),
        ('news', '0006_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPost',
            new_name='News',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='NewsComment',
        ),
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ['-created_at']},
        ),
    ]
