# Generated by Django 4.2.5 on 2023-09-23 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_alter_report_options'),
        ('news', '0007_rename_newspost_news_rename_comment_newscomment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsPost',
        ),
    ]
